name: Deploy to VM

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to VM
        run: |
          # Replace with your actual script or commands to copy files to VM
          cp -r ./github-recovery-codes.txt tpadala@172.17.10.192:C:\Users\tpadala
